"use client";

import { LocalizedLink as Link } from "@/components/localized-link";
import { AdSlot } from "@/components/ad-slot";
import { Icon } from "@/components/icon";
import { useLanguage } from "@/components/language-provider";
import type { GuideConfig } from "@/lib/guide-registry";

export function GuideDetail({ guide }: { guide: GuideConfig }) {
  const { language } = useLanguage(); const hi = language === "hi";
  return <main className="guide-detail-page"><section className="guide-detail-hero"><nav className="breadcrumbs"><Link href="/">{hi ? "होम" : "Home"}</Link><span>/</span><Link href="/guides">{hi ? "गाइड" : "Guides"}</Link><span>/</span><span>{hi ? guide.titleHi : guide.title}</span></nav><span className="kicker"><Icon name={guide.icon} size={17} />{hi ? "व्यावहारिक यात्रा गाइड" : "Practical journey guide"}</span><h1>{hi ? guide.titleHi : guide.title}</h1><p>{hi ? guide.descriptionHi : guide.description}</p><div><span><Icon name="shield" size={16} />{hi ? "स्रोत-जागरूक सलाह" : "Source-aware guidance"}</span><span><Icon name="globe" size={16} />{hi ? "हिंदी और English" : "English and हिंदी"}</span></div></section><AdSlot placement="top" format="970 × 90 / 320 × 100" /><article className="guide-article">{guide.sections.map((section, index) => <section key={section.title}><span>{String(index + 1).padStart(2, "0")}</span><div><h2>{hi ? section.titleHi : section.title}</h2><p>{hi ? section.bodyHi : section.body}</p>{section.points && <ul>{(hi ? section.pointsHi : section.points)?.map((point) => <li key={point}><Icon name="check" size={16} />{point}</li>)}</ul>}</div></section>)}</article><section className="guide-source-note"><span><Icon name="shield" size={25} /></span><div><h2>{hi ? "नियम बदल सकते हैं" : "Rules can change"}</h2><p>{hi ? "किराया, समय, पात्रता, कोटा और रिफंड के अंतिम नियम हमेशा आधिकारिक भारतीय रेल या IRCTC सेवा पर सत्यापित करें।" : "Always verify final fare, timing, eligibility, quota and refund rules through an official Indian Railways or IRCTC service."}</p></div><a href="https://www.indianrail.gov.in/" target="_blank" rel="noreferrer">{hi ? "आधिकारिक स्रोत" : "Official source"}<Icon name="external" size={15} /></a></section><section className="guide-next"><div><span className="kicker light">{hi ? "अब योजना बनाएँ" : "Put it into practice"}</span><h2>{hi ? "यात्रा टूल्स खोलें।" : "Open the journey tools."}</h2></div><Link href="/tools">{hi ? "सभी रेलवे टूल्स" : "All railway tools"}<Icon name="arrow" size={17} /></Link></section></main>;
}
