"use client";

import { LocalizedLink as Link } from "@/components/localized-link";
import { FormEvent, useState } from "react";
import { AdSlot } from "@/components/ad-slot";
import { Icon } from "@/components/icon";
import { useLanguage } from "@/components/language-provider";
import type { ContentPage } from "@/lib/content-registry";

export function ContentPageClient({ page }: { page: ContentPage }) {
  const { language } = useLanguage(); const hi = language === "hi";
  return <main className="content-page"><section className="content-hero"><nav className="breadcrumbs"><Link href="/">{hi ? "होम" : "Home"}</Link><span>/</span><span>{hi ? page.eyebrowHi : page.eyebrow}</span></nav><span className="kicker">{hi ? page.eyebrowHi : page.eyebrow}</span><h1>{hi ? page.titleHi : page.title}</h1><p>{hi ? page.descriptionHi : page.description}</p>{page.updated && <small>{hi ? "अंतिम अपडेट" : "Last updated"}: {page.updated}</small>}</section><AdSlot placement="top" format="970 × 90 / 320 × 100" /><article className="content-article">{page.sections.map((section, index) => <section key={section.title}><span>{String(index + 1).padStart(2, "0")}</span><div><h2>{hi ? section.titleHi : section.title}</h2><p>{hi ? section.bodyHi : section.body}</p>{section.bullets && <ul>{(hi ? section.bulletsHi : section.bullets)?.map((bullet) => <li key={bullet}><Icon name="check" size={16} />{bullet}</li>)}</ul>}</div></section>)}{page.slug === "contact" && <ContactForm hi={hi} />}{page.slug === "official-services" && <OfficialLinks hi={hi} />}</article><section className="content-footer-note"><span><Icon name="shield" size={24} /></span><div><h2>{hi ? "सवाल या सुधार?" : "A question or correction?"}</h2><p>{hi ? "संवेदनशील टिकट जानकारी साझा किए बिना हमारी संपर्क प्रक्रिया इस्तेमाल करें।" : "Use the contact process without sharing sensitive ticket information."}</p></div>{page.slug !== "contact" && <Link href="/contact">{hi ? "संपर्क करें" : "Contact us"}<Icon name="arrow" size={15} /></Link>}</section></main>;
}

function ContactForm({ hi }: { hi: boolean }) {
  const [form, setForm] = useState({ name: "", email: "", topic: "feedback", message: "" }); const [status, setStatus] = useState(""); const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setLoading(true); setStatus(""); try { const response = await fetch("/api/contact", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(form) }); const payload = await response.json() as { message?: string }; setStatus(response.ok ? (hi ? "संदेश सुरक्षित रूप से मिल गया।" : "Your message was received securely.") : String(payload.message ?? (hi ? "अभी संदेश नहीं भेजा जा सका।" : "The message could not be sent."))); if (response.ok) setForm({ name: "", email: "", topic: "feedback", message: "" }); } catch { setStatus(hi ? "कनेक्शन नहीं हो सका।" : "Could not connect."); } finally { setLoading(false); } }
  return <form className="contact-form" onSubmit={submit}><span className="kicker">{hi ? "सुरक्षित संपर्क फॉर्म" : "Secure contact form"}</span><div><label><span>{hi ? "नाम" : "Name"}</span><input required maxLength={80} value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></label><label><span>{hi ? "ईमेल" : "Email"}</span><input required type="email" maxLength={180} value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} /></label><label><span>{hi ? "विषय" : "Topic"}</span><select value={form.topic} onChange={(event) => setForm({ ...form, topic: event.target.value })}><option value="feedback">{hi ? "प्रतिक्रिया" : "Product feedback"}</option><option value="correction">{hi ? "सुधार" : "Correction"}</option><option value="accessibility">{hi ? "सुगमता" : "Accessibility"}</option><option value="advertising">{hi ? "विज्ञापन" : "Advertising"}</option></select></label><label className="message-field"><span>{hi ? "संदेश" : "Message"}</span><textarea required minLength={10} maxLength={3000} value={form.message} onChange={(event) => setForm({ ...form, message: event.target.value })} /></label></div><button disabled={loading}>{loading ? (hi ? "भेज रहे हैं…" : "Sending…") : (hi ? "संदेश भेजें" : "Send message")}<Icon name="arrow" size={17} /></button><small>{hi ? "PNR, OTP, पासवर्ड या भुगतान जानकारी न भेजें।" : "Do not send a PNR, OTP, password or payment information."}</small>{status && <p>{status}</p>}</form>;
}

function OfficialLinks({ hi }: { hi: boolean }) { const links = [["IRCTC", "https://www.irctc.co.in/", hi ? "आधिकारिक टिकट बुकिंग" : "Official ticket booking"], ["NTES", "https://enquiry.indianrail.gov.in/", hi ? "आधिकारिक ट्रेन पूछताछ" : "Official train enquiry"], ["RailMadad", "https://railmadad.indianrailways.gov.in/", hi ? "यात्री सहायता" : "Passenger assistance"]]; return <div className="official-link-grid">{links.map(([name, href, label]) => <a href={href} target="_blank" rel="noreferrer" key={href}><span>{label}</span><h3>{name}</h3><Icon name="external" size={18} /></a>)}</div>; }
