export type ContentSection = { title: string; titleHi: string; body: string; bodyHi: string; bullets?: string[]; bulletsHi?: string[] };
export type ContentPage = { slug: string; title: string; titleHi: string; eyebrow: string; eyebrowHi: string; description: string; descriptionHi: string; updated?: string; sections: ContentSection[] };

export const contentPages: ContentPage[] = [
  { slug: "about", title: "Built around the Indian passenger", titleHi: "भारतीय यात्री के लिए बनाया गया", eyebrow: "About RailSahayak", eyebrowHi: "RailSahayak के बारे में", description: "RailSahayak brings railway tools, explanations and official verification links into one calm bilingual experience.", descriptionHi: "RailSahayak रेलवे टूल्स, सरल जानकारी और आधिकारिक सत्यापन लिंक को एक सहज द्विभाषी अनुभव में लाता है।", sections: [
    { title: "Our purpose", titleHi: "हमारा उद्देश्य", body: "A railway journey creates many small questions. Our purpose is to answer them in the order a traveller needs them—without hiding the answer behind noise.", bodyHi: "रेल यात्रा में कई छोटे सवाल आते हैं। हमारा उद्देश्य उन्हें यात्री की जरूरत के क्रम में जवाब देना है—बिना अनावश्यक शोर के।" },
    { title: "Independent by design", titleHi: "स्वतंत्र सेवा", body: "RailSahayak is not Indian Railways or IRCTC. We connect approved data providers, clearly label estimates and point passengers back to official services for final decisions.", bodyHi: "RailSahayak भारतीय रेल या IRCTC नहीं है। हम स्वीकृत डेटा प्रदाता जोड़ते हैं, अनुमानों को स्पष्ट दिखाते हैं और अंतिम निर्णय के लिए आधिकारिक सेवाओं की ओर ले जाते हैं।" },
    { title: "What we optimise for", titleHi: "हमारी प्राथमिकताएँ", body: "Fast mobile pages, accessible forms, Hindi and English, honest confidence labels, privacy-aware analytics and advertising that never disguises itself as a result.", bodyHi: "तेज़ मोबाइल पेज, सुगम फॉर्म, हिंदी और English, ईमानदार भरोसा लेबल, गोपनीय एनालिटिक्स और परिणाम जैसा न दिखने वाला विज्ञापन।" },
  ]},
  { slug: "contact", title: "Contact RailSahayak", titleHi: "RailSahayak से संपर्क", eyebrow: "Questions and feedback", eyebrowHi: "सवाल और प्रतिक्रिया", description: "Send a correction, partnership query, accessibility issue or product suggestion through the secure contact form.", descriptionHi: "सुधार, साझेदारी, सुगमता समस्या या उत्पाद सुझाव सुरक्षित संपर्क फॉर्म से भेजें।", sections: [
    { title: "Before you send", titleHi: "भेजने से पहले", body: "Never include a full PNR, OTP, password, card number, Aadhaar number or another passenger’s personal information. RailSahayak cannot book, cancel or modify an official railway ticket.", bodyHi: "पूरा PNR, OTP, पासवर्ड, कार्ड नंबर, आधार नंबर या किसी दूसरे यात्री की निजी जानकारी न भेजें। RailSahayak आधिकारिक टिकट बुक, रद्द या बदल नहीं सकता।" },
  ]},
  { slug: "methodology", title: "How RailSahayak reaches an answer", titleHi: "RailSahayak उत्तर कैसे तैयार करता है", eyebrow: "Methodology", eyebrowHi: "हमारी प्रक्रिया", description: "A transparent separation between provider data, calculations, historical signals and official authority.", descriptionHi: "प्रदाता डेटा, गणना, ऐतिहासिक संकेत और आधिकारिक स्रोत के बीच स्पष्ट अंतर।", sections: [
    { title: "Provider data", titleHi: "प्रदाता डेटा", body: "PNR, live running and reservation-dependent results are requested server-side from an approved provider. The browser never receives the provider key.", bodyHi: "PNR, लाइव रनिंग और आरक्षण-आधारित परिणाम सर्वर से स्वीकृत प्रदाता द्वारा लिए जाते हैं। ब्राउज़र को प्रदाता कुंजी नहीं मिलती।" },
    { title: "Calculations and estimates", titleHi: "गणना और अनुमान", body: "Date, berth and connection tools apply documented rules or transparent heuristics. Every estimate is labelled and should be rechecked when the underlying rule can change.", bodyHi: "तारीख, बर्थ और कनेक्शन टूल्स स्पष्ट नियम या अनुमान उपयोग करते हैं। हर अनुमान पर लेबल है और बदलने वाले नियमों को फिर जाँचना चाहिए।" },
    { title: "Confidence labels", titleHi: "भरोसा लेबल", body: "Provider data means it came from the connected feed. Planning estimate means it was calculated. Official link means the final decision belongs on the linked railway service. Not available means we do not know.", bodyHi: "प्रदाता डेटा जुड़ी फ़ीड से आता है। योजना अनुमान गणना है। आधिकारिक लिंक पर अंतिम निर्णय होता है। उपलब्ध नहीं का अर्थ है कि हमें जानकारी नहीं मिली।" },
  ]},
  { slug: "corrections", title: "Corrections policy", titleHi: "सुधार नीति", eyebrow: "Accuracy and accountability", eyebrowHi: "सटीकता और जवाबदेही", description: "How rule changes, factual errors and unclear labels are reviewed and corrected.", descriptionHi: "नियम बदलाव, तथ्यात्मक गलती और अस्पष्ट लेबल की समीक्षा व सुधार कैसे होता है।", sections: [
    { title: "Report with evidence", titleHi: "प्रमाण के साथ रिपोर्ट करें", body: "Use the contact form and include the page URL, the exact statement, the date observed and an official source where possible. Do not include sensitive ticket data.", bodyHi: "संपर्क फॉर्म में पेज URL, सही कथन, देखी गई तारीख और संभव हो तो आधिकारिक स्रोत दें। संवेदनशील टिकट डेटा न दें।" },
    { title: "Review order", titleHi: "समीक्षा क्रम", body: "Safety-critical and money-related errors are prioritised, followed by live-data mapping, rule explanations, translations and presentation issues.", bodyHi: "सुरक्षा और पैसे से जुड़ी गलती पहले, फिर लाइव डेटा मैपिंग, नियम, अनुवाद और प्रस्तुति समस्याएँ देखी जाती हैं।" },
    { title: "Visible corrections", titleHi: "दिखने वाले सुधार", body: "Material editorial changes should update the page date or correction note. Provider outages are labelled as availability issues and are not replaced with invented data.", bodyHi: "महत्वपूर्ण संपादकीय बदलाव पर पेज तारीख या सुधार नोट अपडेट होना चाहिए। प्रदाता समस्या को उपलब्धता समस्या दिखाया जाता है, काल्पनिक डेटा नहीं।" },
  ]},
  { slug: "privacy", title: "Privacy policy", titleHi: "गोपनीयता नीति", eyebrow: "Privacy first", eyebrowHi: "गोपनीयता पहले", description: "What RailSahayak processes, why it is needed and the controls required before production launch.", descriptionHi: "RailSahayak कौन-सा डेटा क्यों संसाधित करता है और उत्पादन लॉन्च से पहले कौन-से नियंत्रण जरूरी हैं।", updated: "24 August 2026", sections: [
    { title: "Journey searches", titleHi: "यात्रा खोज", body: "PNR and journey inputs are sent to the site’s server only to answer the request. They must not be placed in URLs, analytics events or application logs. Live providers may process the query under their own terms.", bodyHi: "PNR और यात्रा जानकारी केवल अनुरोध का उत्तर देने के लिए साइट सर्वर पर भेजी जाती है। इन्हें URL, एनालिटिक्स या लॉग में नहीं रखा जाना चाहिए। लाइव प्रदाता अपनी शर्तों के तहत क्वेरी संसाधित कर सकता है।" },
    { title: "Reminder data", titleHi: "रिमाइंडर डेटा", body: "A PNR alert requires explicit consent and an email address. The PNR is encrypted with a server-only key; the database stores ciphertext, an IV and scheduling metadata. Reminder records should expire automatically after the journey or retention period.", bodyHi: "PNR अलर्ट के लिए स्पष्ट सहमति और ईमेल जरूरी है। PNR सर्वर-केवल कुंजी से एन्क्रिप्ट होता है; डेटाबेस में एन्क्रिप्टेड डेटा, IV और समय जानकारी रहती है। यात्रा या रखने की अवधि के बाद रिकॉर्ड अपने-आप समाप्त होना चाहिए।" },
    { title: "Analytics", titleHi: "एनालिटिक्स", body: "RailSahayak can record page views, tool names, broad outcomes and an anonymous session identifier. Full PNRs, passenger names, email addresses and form contents are excluded. IP handling depends on the configured analytics provider and should use available privacy controls.", bodyHi: "RailSahayak पेज व्यू, टूल नाम, सामान्य परिणाम और अनाम सत्र ID रिकॉर्ड कर सकता है। पूरा PNR, यात्री नाम, ईमेल और फॉर्म सामग्री शामिल नहीं होती। IP प्रबंधन एनालिटिक्स प्रदाता पर निर्भर है और उपलब्ध गोपनीयता नियंत्रण उपयोग होने चाहिए।" },
    { title: "Advertising and cookies", titleHi: "विज्ञापन और कुकीज़", body: "Advertising services may use cookies or similar identifiers after the consent setup required for the visitor’s region. Ads are labelled and kept separate from railway results. Do not enable personalised ads before the necessary consent and policy configuration is complete.", bodyHi: "विज्ञापन सेवाएँ क्षेत्र के अनुसार जरूरी सहमति के बाद कुकी या समान पहचान उपयोग कर सकती हैं। विज्ञापन स्पष्ट लेबल के साथ रेलवे परिणाम से अलग रहते हैं। आवश्यक सहमति और नीति सेटअप से पहले व्यक्तिगत विज्ञापन चालू न करें।" },
    { title: "Security and retention", titleHi: "सुरक्षा और डेटा अवधि", body: "Secrets belong only in protected hosting variables. Database row-level security, least-privilege keys, encrypted transport and scheduled deletion are required. No internet service can promise absolute security.", bodyHi: "कुंजियाँ केवल सुरक्षित होस्टिंग वेरिएबल में रहें। डेटाबेस RLS, सीमित अधिकार वाली कुंजियाँ, एन्क्रिप्टेड ट्रांसपोर्ट और तय समय पर हटाना जरूरी है। कोई इंटरनेट सेवा पूर्ण सुरक्षा की गारंटी नहीं दे सकती।" },
    { title: "Your choices", titleHi: "आपके विकल्प", body: "Visitors can avoid reminders, reject optional cookies where offered and request deletion of contact or reminder data through the contact page. Identity verification may be required before fulfilling a request.", bodyHi: "उपयोगकर्ता रिमाइंडर न चुन सकते हैं, उपलब्ध होने पर वैकल्पिक कुकी अस्वीकार कर सकते हैं और संपर्क पेज से संपर्क या रिमाइंडर डेटा हटाने का अनुरोध कर सकते हैं। अनुरोध से पहले पहचान सत्यापन जरूरी हो सकता है।" },
  ]},
  { slug: "terms", title: "Terms of use", titleHi: "उपयोग की शर्तें", eyebrow: "Use RailSahayak responsibly", eyebrowHi: "RailSahayak का जिम्मेदार उपयोग", description: "The boundaries of this independent information service and the visitor’s responsibilities.", descriptionHi: "इस स्वतंत्र सूचना सेवा की सीमाएँ और उपयोगकर्ता की जिम्मेदारियाँ।", updated: "24 August 2026", sections: [
    { title: "Information service", titleHi: "सूचना सेवा", body: "RailSahayak provides tools, estimates, explanations and links. It is not a booking agent, railway authority or guarantee of a seat, refund, platform, punctuality or journey outcome.", bodyHi: "RailSahayak टूल्स, अनुमान, जानकारी और लिंक देता है। यह बुकिंग एजेंट या रेलवे प्राधिकरण नहीं और सीट, रिफंड, प्लेटफॉर्म, समय या यात्रा परिणाम की गारंटी नहीं देता।" },
    { title: "Acceptable use", titleHi: "स्वीकार्य उपयोग", body: "Do not probe, overload, scrape contrary to published controls, bypass rate limits, submit another person’s data without authority or use the service for fraud.", bodyHi: "सिस्टम की जाँच या ओवरलोड, नियंत्रण के विरुद्ध स्क्रैपिंग, रेट लिमिट बायपास, बिना अधिकार दूसरे का डेटा या धोखाधड़ी के लिए सेवा उपयोग न करें।" },
    { title: "Third-party services", titleHi: "तीसरे पक्ष की सेवाएँ", body: "Live data, official booking, analytics, advertising, email and hosting may be supplied by third parties. Their availability and terms apply to their services.", bodyHi: "लाइव डेटा, आधिकारिक बुकिंग, एनालिटिक्स, विज्ञापन, ईमेल और होस्टिंग तीसरे पक्ष से हो सकते हैं। उनकी सेवा पर उनकी उपलब्धता और शर्तें लागू होती हैं।" },
    { title: "Changes and availability", titleHi: "बदलाव और उपलब्धता", body: "Features may be changed, rate-limited or withdrawn for security, legal, provider or operational reasons. Material terms should show a revised effective date.", bodyHi: "सुरक्षा, कानूनी, प्रदाता या संचालन कारण से सुविधाएँ बदल, सीमित या बंद हो सकती हैं। महत्वपूर्ण शर्त बदलाव पर नई प्रभावी तारीख दिखनी चाहिए।" },
  ]},
  { slug: "disclaimer", title: "Railway information disclaimer", titleHi: "रेलवे जानकारी अस्वीकरण", eyebrow: "Important boundaries", eyebrowHi: "महत्वपूर्ण सीमाएँ", description: "Live feeds can be delayed, calculations can have exceptions and official railway records remain final.", descriptionHi: "लाइव फ़ीड में देरी हो सकती है, गणना में अपवाद हो सकते हैं और आधिकारिक रेलवे रिकॉर्ड अंतिम है।", sections: [
    { title: "Not official", titleHi: "आधिकारिक नहीं", body: "RailSahayak is an independent utility and is not affiliated with Indian Railways, IRCTC or the Ministry of Railways unless a specific written partnership is announced.", bodyHi: "RailSahayak एक स्वतंत्र सुविधा है और किसी लिखित साझेदारी की घोषणा के बिना भारतीय रेल, IRCTC या रेल मंत्रालय से संबद्ध नहीं है।" },
    { title: "Live data can change", titleHi: "लाइव डेटा बदल सकता है", body: "PNR, running, platform, coach, availability and fare information can change after the displayed time. Network or provider delays may make a result incomplete.", bodyHi: "PNR, रनिंग, प्लेटफॉर्म, कोच, उपलब्धता और किराया दिखाई गई जानकारी के बाद बदल सकते हैं। नेटवर्क या प्रदाता देरी से परिणाम अधूरा हो सकता है।" },
    { title: "Calculators are planning aids", titleHi: "कैलकुलेटर योजना सहायता हैं", body: "Booking, Tatkal, chart, cancellation, refund, luggage and connection results are estimates. Special trains, stations, quotas, circulars and ticket conditions can create exceptions.", bodyHi: "बुकिंग, तत्काल, चार्ट, रद्दीकरण, रिफंड, सामान और कनेक्शन परिणाम अनुमान हैं। विशेष ट्रेन, स्टेशन, कोटा, सर्कुलर और टिकट शर्तों में अपवाद हो सकते हैं।" },
  ]},
  { slug: "advertise", title: "Advertise with RailSahayak", titleHi: "RailSahayak पर विज्ञापन", eyebrow: "Useful, clearly labelled advertising", eyebrowHi: "उपयोगी और स्पष्ट विज्ञापन", description: "Reach Indian railway travellers without interrupting the answer they came to find.", descriptionHi: "भारतीय रेल यात्रियों तक पहुँचें—जिस उत्तर के लिए वे आए हैं उसे बाधित किए बिना।", sections: [
    { title: "Available placements", titleHi: "उपलब्ध विज्ञापन स्थान", body: "The design includes responsive leaderboards after primary tools, in-content rectangles beside guides and lower-page placements. Inventory can be served through AdSense or direct campaigns.", bodyHi: "डिज़ाइन में मुख्य टूल के बाद रिस्पॉन्सिव लीडरबोर्ड, गाइड के पास इन-कंटेंट आयत और नीचे के स्थान हैं। इन्हें AdSense या सीधे अभियान से चलाया जा सकता है।", bullets: ["Desktop leaderboard: up to 970 × 90", "Mobile responsive: approximately 320 × 100", "In-content rectangle: 300 × 250"], bulletsHi: ["डेस्कटॉप लीडरबोर्ड: 970 × 90 तक", "मोबाइल रिस्पॉन्सिव: लगभग 320 × 100", "इन-कंटेंट आयत: 300 × 250"] },
    { title: "Editorial separation", titleHi: "संपादकीय अलगाव", body: "Ads are labelled, never placed inside the primary result and never styled as an official railway button. Sponsors cannot buy a confidence label or alter a calculation.", bodyHi: "विज्ञापन लेबल के साथ, मुख्य परिणाम से अलग और आधिकारिक रेलवे बटन जैसे नहीं होते। प्रायोजक भरोसा लेबल खरीद या गणना बदल नहीं सकते।" },
    { title: "Campaign requests", titleHi: "अभियान अनुरोध", body: "Use the contact page with the brand, destination URL, target geography, dates and proposed creative size. Travel, financial and regulated advertising may require additional review.", bodyHi: "संपर्क पेज पर ब्रांड, लिंक, लक्षित क्षेत्र, तारीख और रचनात्मक आकार भेजें। यात्रा, वित्तीय और विनियमित विज्ञापन की अतिरिक्त समीक्षा हो सकती है।" },
  ]},
  { slug: "alerts", title: "Railway alerts and reminders", titleHi: "रेलवे अलर्ट और रिमाइंडर", eyebrow: "Be ready at the right time", eyebrowHi: "सही समय पर तैयार रहें", description: "Set privacy-aware PNR monitoring and calendar reminders without giving away sensitive details.", descriptionHi: "संवेदनशील जानकारी साझा किए बिना गोपनीय PNR मॉनिटरिंग और कैलेंडर रिमाइंडर बनाएँ।", sections: [
    { title: "PNR change alerts", titleHi: "PNR बदलाव अलर्ट", body: "With explicit consent, the server can encrypt a PNR, recheck it on a schedule and email only when the status changes. Production delivery needs Supabase, a cron job and an email provider.", bodyHi: "स्पष्ट सहमति पर सर्वर PNR एन्क्रिप्ट कर तय समय पर जाँच और स्थिति बदलने पर ईमेल भेज सकता है। उत्पादन के लिए Supabase, cron job और ईमेल प्रदाता चाहिए।" },
    { title: "Booking reminders", titleHi: "बुकिंग रिमाइंडर", body: "Booking and Tatkal calculators can create a local calendar file. The reminder remains on the visitor’s device or chosen calendar service.", bodyHi: "बुकिंग और तत्काल कैलकुलेटर स्थानीय कैलेंडर फाइल बनाते हैं। रिमाइंडर उपयोगकर्ता के डिवाइस या चुनी कैलेंडर सेवा में रहता है।" },
  ]},
  { slug: "railway-updates", title: "Railway rule updates", titleHi: "रेलवे नियम अपडेट", eyebrow: "Review queue", eyebrowHi: "समीक्षा सूची", description: "A transparent place for reviewed changes that affect calculators, guidance and passenger decisions.", descriptionHi: "कैलकुलेटर, गाइड और यात्री निर्णय पर असर डालने वाले समीक्षा किए बदलावों की स्पष्ट जगह।", sections: [
    { title: "What belongs here", titleHi: "यहाँ क्या आएगा", body: "Reviewed changes to reservation windows, Tatkal timings, charting, cancellation, refunds, quotas, luggage rules and passenger services should be summarised with an effective date and official source.", bodyHi: "आरक्षण अवधि, तत्काल समय, चार्ट, रद्दीकरण, रिफंड, कोटा, सामान नियम और यात्री सेवा बदलाव प्रभावी तारीख व आधिकारिक स्रोत के साथ यहाँ आएँगे।" },
    { title: "No unverified news feed", titleHi: "असत्यापित समाचार फ़ीड नहीं", body: "Until an update is sourced and reviewed, it should not change a calculator or appear as settled guidance. Social posts can be leads, not final authority.", bodyHi: "स्रोत और समीक्षा से पहले कोई अपडेट कैलकुलेटर नहीं बदलेगा या पक्का नियम नहीं बनेगा। सोशल पोस्ट संकेत हो सकते हैं, अंतिम स्रोत नहीं।" },
  ]},
  { slug: "blog", title: "RailSahayak journal", titleHi: "RailSahayak जर्नल", eyebrow: "Practical travel notes", eyebrowHi: "व्यावहारिक यात्रा नोट्स", description: "Deep explanations, product updates and seasonal planning notes for Indian railway passengers.", descriptionHi: "भारतीय रेल यात्रियों के लिए विस्तृत जानकारी, उत्पाद अपडेट और मौसमी यात्रा नोट्स।", sections: [
    { title: "Start with the guide library", titleHi: "गाइड लाइब्रेरी से शुरुआत करें", body: "The guide library already covers booking, Tatkal, refunds, PNR, coaches, charting, alternate routes, family journeys, stations and festival planning.", bodyHi: "गाइड लाइब्रेरी में बुकिंग, तत्काल, रिफंड, PNR, कोच, चार्ट, वैकल्पिक रूट, परिवार, स्टेशन और त्योहार यात्रा शामिल हैं।" },
    { title: "Publishing standard", titleHi: "प्रकाशन मानक", body: "Every article that states a changeable railway rule should include a source, review date and a plain-language distinction between a rule and an estimate.", bodyHi: "बदलने वाले रेलवे नियम वाले हर लेख में स्रोत, समीक्षा तारीख और नियम व अनुमान का सरल अंतर होना चाहिए।" },
  ]},
  { slug: "official-services", title: "Official railway services", titleHi: "आधिकारिक रेलवे सेवाएँ", eyebrow: "Final verification and action", eyebrowHi: "अंतिम सत्यापन और कार्रवाई", description: "Use the right official destination for booking, live enquiry and passenger assistance.", descriptionHi: "बुकिंग, लाइव पूछताछ और यात्री सहायता के लिए सही आधिकारिक सेवा चुनें।", sections: [
    { title: "IRCTC", titleHi: "IRCTC", body: "Use the official IRCTC website or app for ticket booking, account actions and the options shown against an online booking.", bodyHi: "टिकट बुकिंग, खाता कार्रवाई और ऑनलाइन बुकिंग से जुड़े विकल्प के लिए आधिकारिक IRCTC वेबसाइट या ऐप उपयोग करें।" },
    { title: "NTES", titleHi: "NTES", body: "Use National Train Enquiry System for official train running and station enquiry. Station displays and announcements can reflect the latest local operational change.", bodyHi: "आधिकारिक ट्रेन रनिंग और स्टेशन पूछताछ के लिए NTES उपयोग करें। स्टेशन डिस्प्ले और घोषणा नवीनतम स्थानीय बदलाव दिखा सकते हैं।" },
    { title: "RailMadad", titleHi: "RailMadad", body: "Use RailMadad for applicable passenger assistance and complaints. Keep the reference number and share only the data necessary for the issue.", bodyHi: "यात्री सहायता और लागू शिकायतों के लिए RailMadad उपयोग करें। संदर्भ नंबर रखें और केवल जरूरी जानकारी साझा करें।" },
  ]},
];

export function getContentPage(slug: string) { return contentPages.find((page) => page.slug === slug); }
