export type GuideSection = { title: string; titleHi: string; body: string; bodyHi: string; points?: string[]; pointsHi?: string[] };
export type GuideConfig = { slug: string; title: string; titleHi: string; description: string; descriptionHi: string; icon: string; sections: GuideSection[] };

export const guides: GuideConfig[] = [
  { slug: "booking-and-advance-reservation", title: "Booking and Advance Reservation", titleHi: "बुकिंग और अग्रिम आरक्षण", description: "Plan when to book, which details to prepare and how to verify the final reservation.", descriptionHi: "कब बुक करना है, कौन-सी जानकारी तैयार रखनी है और अंतिम आरक्षण कैसे सत्यापित करना है।", icon: "calendar", sections: [
    { title: "Start with the journey, not the train", titleHi: "ट्रेन नहीं, यात्रा से शुरुआत करें", body: "Fix your acceptable departure window, arrival deadline, boarding station and class before comparing trains. This keeps a popular train from becoming the only plan.", bodyHi: "ट्रेनें देखने से पहले प्रस्थान का समय, पहुँचने की सीमा, बोर्डिंग स्टेशन और श्रेणी तय करें। इससे किसी एक लोकप्रिय ट्रेन पर निर्भरता कम होती है।", points: ["Compare nearby stations and dates", "Keep passenger names and ages ready", "Check the train’s originating-date rule"], pointsHi: ["पास के स्टेशन और तारीखें भी देखें", "यात्रियों के नाम और आयु तैयार रखें", "ट्रेन के शुरुआती स्टेशन की तारीख जाँचें"] },
    { title: "Use the opening date as a reminder", titleHi: "बुकिंग खुलने की तारीख का रिमाइंडर रखें", body: "Reservation windows and exceptions can change. Use the booking-date calculator for planning, then confirm the current rule on IRCTC before payment.", bodyHi: "आरक्षण अवधि और अपवाद बदल सकते हैं। योजना के लिए बुकिंग तारीख कैलकुलेटर इस्तेमाल करें और भुगतान से पहले IRCTC पर मौजूदा नियम जाँचें।" },
    { title: "Verify after payment", titleHi: "भुगतान के बाद सत्यापन करें", body: "A payment message is not the same as a booked ticket. Confirm that the PNR and booking status appear in your official account or ticket record.", bodyHi: "भुगतान संदेश टिकट बनने का प्रमाण नहीं है। आधिकारिक खाते या टिकट रिकॉर्ड में PNR और बुकिंग स्थिति अवश्य देखें।" },
  ]},
  { slug: "tatkal", title: "Tatkal", titleHi: "तत्काल", description: "Prepare for time-sensitive Tatkal booking without relying on shortcuts or unsafe claims.", descriptionHi: "शॉर्टकट या असुरक्षित दावों पर निर्भर हुए बिना समय-संवेदनशील तत्काल बुकिंग की तैयारी करें।", icon: "clock", sections: [
    { title: "Prepare before the opening minute", titleHi: "खुलने के समय से पहले तैयारी करें", body: "Sign in early, save the passenger list where permitted, confirm the train’s origin date and decide your acceptable class and boarding station.", bodyHi: "पहले लॉग इन करें, जहाँ अनुमति हो वहाँ यात्री सूची सहेजें, ट्रेन की शुरुआती तारीख जाँचें और स्वीकार्य श्रेणी व बोर्डिंग स्टेशन तय रखें।" },
    { title: "Understand what may differ", titleHi: "क्या अलग हो सकता है समझें", body: "Class groups can have different opening times. Availability, payment completion and booking confirmation remain separate steps.", bodyHi: "श्रेणी समूहों के खुलने का समय अलग हो सकता है। उपलब्धता, भुगतान पूरा होना और टिकट कन्फर्म होना अलग-अलग चरण हैं।" },
    { title: "Keep a safe fallback", titleHi: "सुरक्षित विकल्प रखें", body: "Prepare a second train, another class or a nearby station. Never share OTPs or account credentials with anyone promising guaranteed Tatkal tickets.", bodyHi: "दूसरी ट्रेन, दूसरी श्रेणी या पास का स्टेशन तैयार रखें। गारंटीड तत्काल टिकट का दावा करने वाले किसी व्यक्ति से OTP या खाता जानकारी साझा न करें।" },
  ]},
  { slug: "cancellation-and-refunds", title: "Cancellation and Refunds", titleHi: "रद्दीकरण और रिफंड", description: "Understand timing, deductions and what to keep when a refund needs follow-up.", descriptionHi: "समय, कटौती और रिफंड फॉलो-अप के लिए क्या सुरक्षित रखना है, समझें।", icon: "refund", sections: [
    { title: "Time changes the outcome", titleHi: "समय से परिणाम बदलता है", body: "Refund deductions may depend on ticket status, class, cancellation time, chart status and the reason for the claim. Use the calculator as an estimate, not a settlement promise.", bodyHi: "रिफंड कटौती टिकट स्थिति, श्रेणी, रद्द करने के समय, चार्ट स्थिति और दावे के कारण पर निर्भर हो सकती है। कैलकुलेटर को अनुमान मानें, गारंटी नहीं।" },
    { title: "Keep an evidence trail", titleHi: "प्रमाण सुरक्षित रखें", body: "Save the PNR, transaction ID, cancellation receipt, timestamps and any official message. Avoid posting the full PNR publicly.", bodyHi: "PNR, लेन-देन ID, रद्दीकरण रसीद, समय और आधिकारिक संदेश सुरक्षित रखें। पूरा PNR सार्वजनिक रूप से साझा न करें।" },
    { title: "Use the correct official channel", titleHi: "सही आधिकारिक माध्यम चुनें", body: "The correct flow can differ for an online cancellation, a failed booking, a train disruption or a TDR-type claim. Follow the option shown in your official booking account and use RailMadad when applicable.", bodyHi: "ऑनलाइन रद्दीकरण, असफल बुकिंग, ट्रेन व्यवधान या TDR जैसे दावे की प्रक्रिया अलग हो सकती है। आधिकारिक बुकिंग खाते में दिखे विकल्प का पालन करें और जहाँ लागू हो RailMadad उपयोग करें।" },
  ]},
  { slug: "pnr-and-waiting-lists", title: "PNR and Waiting Lists", titleHi: "PNR और प्रतीक्षा सूची", description: "Read CNF, RAC and waiting-list changes without treating predictions as guarantees.", descriptionHi: "CNF, RAC और वेटलिस्ट बदलाव समझें—भविष्यवाणी को गारंटी न मानें।", icon: "ticket", sections: [
    { title: "Read booking and current status separately", titleHi: "बुकिंग और वर्तमान स्थिति अलग पढ़ें", body: "The original booking status records where the passenger started. Current status shows the latest position and may continue changing until charting.", bodyHi: "बुकिंग स्थिति शुरुआती स्थिति बताती है। वर्तमान स्थिति नया स्थान बताती है और चार्ट बनने तक बदल सकती है।" },
    { title: "Category matters", titleHi: "श्रेणी मायने रखती है", body: "GNWL, RLWL, PQWL and TQWL are different quota-linked categories. Compare like with like; one historical trend should not be applied to every route.", bodyHi: "GNWL, RLWL, PQWL और TQWL अलग कोटा-आधारित श्रेणियाँ हैं। अलग रूट पर एक ही ऐतिहासिक रुझान लागू न करें।" },
    { title: "Check the final travel authority", titleHi: "अंतिम यात्रा अनुमति जाँचें", body: "Verify the final PNR status and applicable e-ticket travel rule through official channels before boarding. A third-party probability is not authority to travel.", bodyHi: "बोर्डिंग से पहले अंतिम PNR स्थिति और ई-टिकट यात्रा नियम आधिकारिक माध्यम से जाँचें। किसी तीसरे पक्ष की संभावना यात्रा अनुमति नहीं है।" },
  ]},
  { slug: "train-classes-and-coaches", title: "Train Classes and Coaches", titleHi: "ट्रेन श्रेणियाँ और कोच", description: "Compare accommodation, berth patterns and coach information before choosing a class.", descriptionHi: "श्रेणी चुनने से पहले सुविधा, बर्थ पैटर्न और कोच जानकारी की तुलना करें।", icon: "seat", sections: [
    { title: "Choose for the journey length", titleHi: "यात्रा अवधि के अनुसार चुनें", body: "Balance sleeping needs, daytime seating, privacy, air-conditioning and budget. The same class can feel different on an overnight journey and a short daytime trip.", bodyHi: "सोने की जरूरत, दिन की सीट, गोपनीयता, AC और बजट का संतुलन देखें। वही श्रेणी रात की और छोटी दिन की यात्रा में अलग अनुभव दे सकती है।" },
    { title: "A layout is representative", titleHi: "लेआउट प्रतिनिधि होता है", body: "Coach diagrams help identify common berth patterns, but the actual rake, coach series and accessible fixtures can differ. Check the final coach and berth on the chart or ticket.", bodyHi: "कोच चित्र सामान्य बर्थ पैटर्न समझाते हैं, पर वास्तविक रेक, कोच श्रृंखला और सुविधाएँ अलग हो सकती हैं। अंतिम कोच और बर्थ चार्ट या टिकट पर देखें।" },
    { title: "Board using the final position", titleHi: "अंतिम स्थिति के अनुसार बोर्ड करें", body: "Coach position and platform can change. Recheck the station display and announcement, especially close to departure.", bodyHi: "कोच और प्लेटफॉर्म बदल सकते हैं। प्रस्थान के पास स्टेशन डिस्प्ले और घोषणा फिर देखें।" },
  ]},
  { slug: "chart-preparation", title: "Chart Preparation", titleHi: "चार्ट तैयारी", description: "Know what charting changes and how to plan around an estimated chart time.", descriptionHi: "चार्ट बनने से क्या बदलता है और अनुमानित समय के आसपास योजना कैसे बनाएँ।", icon: "chart", sections: [
    { title: "Why charting matters", titleHi: "चार्ट क्यों महत्वपूर्ण है", body: "Charting finalises many passenger allocations and can change RAC, waitlist, coach and berth details. Some systems may show updates in stages.", bodyHi: "चार्ट कई यात्री आवंटन तय करता है और RAC, वेटलिस्ट, कोच व बर्थ बदल सकते हैं। कुछ सिस्टम चरणों में अपडेट दिखाते हैं।" },
    { title: "Treat time as an estimate", titleHi: "समय को अनुमान मानें", body: "Chart preparation varies by departure time, boarding point and operational instruction. Use the calculator for a decision window and recheck the official PNR record.", bodyHi: "चार्ट समय प्रस्थान, बोर्डिंग स्टेशन और संचालन निर्देश पर निर्भर करता है। कैलकुलेटर से निर्णय समय समझें और आधिकारिक PNR फिर जाँचें।" },
    { title: "Make a decision checklist", titleHi: "निर्णय सूची बनाएँ", body: "Before the expected chart time, note your cancellation options, alternative travel plan, station reach time and how you will verify the final status.", bodyHi: "अनुमानित चार्ट समय से पहले रद्दीकरण विकल्प, वैकल्पिक यात्रा, स्टेशन पहुँच समय और अंतिम सत्यापन तरीका नोट करें।" },
  ]},
  { slug: "vikalp-and-alternate-routes", title: "VIKALP and Alternate Routes", titleHi: "VIKALP और वैकल्पिक रूट", description: "Plan alternatives while understanding that an option does not guarantee an alternate berth.", descriptionHi: "यह समझते हुए विकल्प बनाएँ कि विकल्प चुनना वैकल्पिक बर्थ की गारंटी नहीं है।", icon: "route", sections: [
    { title: "Eligibility is only the first step", titleHi: "पात्रता केवल पहला चरण है", body: "The option generally relates to eligible waitlisted bookings and selected trains or routes. An alternate allocation depends on the scheme rules and availability.", bodyHi: "यह विकल्प सामान्यतः पात्र वेटलिस्ट बुकिंग और चुनी हुई ट्रेनों या रूट से जुड़ा होता है। वैकल्पिक आवंटन नियम और उपलब्धता पर निर्भर है।" },
    { title: "Compare the complete alternate journey", titleHi: "पूरी वैकल्पिक यात्रा की तुलना करें", body: "Check the alternate departure time, boarding station, arrival time and onward connection—not only the train name.", bodyHi: "सिर्फ ट्रेन का नाम नहीं, वैकल्पिक प्रस्थान, बोर्डिंग स्टेशन, आगमन और आगे की कनेक्शन भी जाँचें।" },
    { title: "Build independent fallbacks", titleHi: "स्वतंत्र विकल्प भी रखें", body: "Nearby stations, split journeys and a later departure can help, but allow a realistic transfer buffer and avoid unprotected tight connections.", bodyHi: "पास के स्टेशन, विभाजित यात्रा और बाद की ट्रेन मदद कर सकती है, पर पर्याप्त कनेक्शन समय रखें और बहुत तंग बदलाव से बचें।" },
  ]},
  { slug: "family-and-senior-citizen-travel", title: "Family and Senior-Citizen Travel", titleHi: "परिवार और वरिष्ठ नागरिक यात्रा", description: "Plan lower-berth needs, assistance, food, medicines and safe station movement.", descriptionHi: "लोअर बर्थ, सहायता, भोजन, दवा और सुरक्षित स्टेशन आवागमन की योजना बनाएँ।", icon: "shield", sections: [
    { title: "Make mobility the first constraint", titleHi: "चलने-फिरने की जरूरत पहले रखें", body: "Choose boarding stations, arrival times and classes around the slowest traveller. Avoid unnecessary footbridges or short transfers where possible.", bodyHi: "बोर्डिंग स्टेशन, समय और श्रेणी सबसे धीमे यात्री की सुविधा अनुसार चुनें। जहाँ संभव हो अनावश्यक फुटब्रिज या कम समय वाले बदलाव से बचें।" },
    { title: "Requests are not guarantees", titleHi: "अनुरोध गारंटी नहीं होते", body: "A berth preference or quota request can improve planning but may not guarantee a specific berth. Recheck the final allocation and prepare a polite swap request if needed.", bodyHi: "बर्थ पसंद या कोटा अनुरोध योजना में मदद करता है पर निश्चित बर्थ की गारंटी नहीं। अंतिम आवंटन देखें और जरूरत पर विनम्र सीट बदलने का अनुरोध तैयार रखें।" },
    { title: "Carry a compact journey kit", titleHi: "छोटी यात्रा किट रखें", body: "Keep medicines, water, identity documents, emergency contacts and essential food accessible rather than deep inside large luggage.", bodyHi: "दवाएँ, पानी, पहचान पत्र, आपात संपर्क और जरूरी भोजन बड़े सामान के अंदर नहीं, आसानी से मिलने वाली जगह रखें।" },
  ]},
  { slug: "station-and-onboard-travel", title: "Station and Onboard Travel", titleHi: "स्टेशन और ट्रेन में यात्रा", description: "Move through the station calmly and know which information can change close to departure.", descriptionHi: "स्टेशन पर सरलता से जाएँ और समझें कि प्रस्थान के पास कौन-सी जानकारी बदल सकती है।", icon: "pin", sections: [
    { title: "Use a two-source check", titleHi: "दो स्रोतों से जाँचें", body: "Use live digital information to plan, then confirm platform and coach position on the station display or announcement. Operational changes can happen late.", bodyHi: "योजना के लिए लाइव डिजिटल जानकारी देखें, फिर स्टेशन डिस्प्ले या घोषणा से प्लेटफॉर्म और कोच स्थिति पक्की करें। संचालन बदलाव देर से हो सकते हैं।" },
    { title: "Protect your boarding margin", titleHi: "बोर्डिंग समय सुरक्षित रखें", body: "Allow time for entry, security, footbridges, long platforms and finding the coach. Large stations and festival crowds need a bigger margin.", bodyHi: "प्रवेश, सुरक्षा, फुटब्रिज, लंबे प्लेटफॉर्म और कोच खोजने के लिए समय रखें। बड़े स्टेशन और त्योहार की भीड़ में अधिक समय चाहिए।" },
    { title: "Know where to get help", titleHi: "मदद कहाँ मिलेगी जानें", body: "For urgent onboard or station issues, use official railway staff and RailMadad. Share only the information necessary for the complaint.", bodyHi: "स्टेशन या ट्रेन में जरूरी समस्या के लिए आधिकारिक रेलवे कर्मचारी और RailMadad उपयोग करें। शिकायत के लिए केवल आवश्यक जानकारी साझा करें।" },
  ]},
  { slug: "festival-travel-planning", title: "Festival Travel Planning", titleHi: "त्योहार यात्रा योजना", description: "Plan for high demand, crowding and schedule risk with practical alternatives.", descriptionHi: "अधिक मांग, भीड़ और समय जोखिम के लिए व्यावहारिक विकल्पों के साथ योजना बनाएँ।", icon: "sparkle", sections: [
    { title: "Plan a window, not one departure", titleHi: "एक ट्रेन नहीं, समय अवधि की योजना बनाएँ", body: "Compare several dates, nearby stations and acceptable classes. Include special trains only after checking their days of run and exact station timings.", bodyHi: "कई तारीखें, पास के स्टेशन और स्वीकार्य श्रेणियाँ देखें। विशेष ट्रेन चुनने से पहले उसके चलने के दिन और सही स्टेशन समय जाँचें।" },
    { title: "Expect crowded station movement", titleHi: "स्टेशन पर भीड़ मानकर चलें", body: "Arrive earlier than usual, keep luggage manageable and decide a family meeting point. Do not rely on mobile connectivity at the last minute.", bodyHi: "सामान्य से पहले पहुँचें, सामान संभालने योग्य रखें और परिवार के मिलने की जगह तय करें। अंतिम समय पर मोबाइल नेटवर्क पर निर्भर न रहें।" },
    { title: "Protect onward plans", titleHi: "आगे की योजना सुरक्षित रखें", body: "Avoid non-refundable onward bookings with a tight connection. Build a delay buffer and keep essential accommodation or ground-transport contacts offline.", bodyHi: "बहुत कम कनेक्शन समय के साथ नॉन-रिफंडेबल आगे की बुकिंग से बचें। देरी का समय रखें और जरूरी होटल या परिवहन संपर्क ऑफलाइन रखें।" },
  ]},
];

export function getGuide(slug: string) { return guides.find((guide) => guide.slug === slug); }
