import type { GuideSection } from "@/lib/guide-registry";
export type GuideReference = { label: string; url: string };
export type GuideAddition = { checked: string; sources: GuideReference[]; tools: string[]; sections: GuideSection[] };
const pnrSource = { label: "Indian Railways: PNR enquiry and status legend", url: "https://www.indianrail.gov.in/enquiry/PNR/PnrEnquiry.html?locale=en" };
const refundSource = { label: "IRCTC: e-ticket cancellation", url: "https://contents.irctc.co.in/en/eticketCancel.html" };
const waitingSource = { label: "IRCTC: fully waitlisted e-tickets", url: "https://contents.irctc.co.in/en/Waitlisted_E-Ticket.html" };
const chartSource = { label: "Central Railway: revised chart timings, July 2025", url: "https://cr.indianrailways.gov.in/view_detail.jsp?dcd=9856&did=1751953668715F08FEB7D1A698517544F5A29DD31BC5D&id=0%2C4%2C268&lang=0" };
export const guideAdditions: Record<string, GuideAddition> = {
  "pnr-status-explained": { checked: "16 September 2026", sources: [pnrSource], tools: ["pnr-status", "status-code-decoder", "coach-position"], sections: [
    { title: "Check the booking before interpreting the status", titleHi: "स्थिति समझने से पहले बुकिंग मिलाएँ", body: "Use the PNR printed on the ticket. Compare the train, boarding date, class and boarding point with your booking. The booking status and current status are separate fields; current status can change before the final chart. An old screenshot is not a fresh enquiry.", bodyHi: "टिकट पर छपा PNR इस्तेमाल करें। ट्रेन, बोर्डिंग तारीख, श्रेणी और बोर्डिंग स्टेशन अपनी बुकिंग से मिलाएँ। बुकिंग और वर्तमान स्थिति अलग हैं; अंतिम चार्ट से पहले वर्तमान स्थिति बदल सकती है। पुराना स्क्रीनशॉट नई जाँच नहीं है।" },
    { title: "Read every passenger row", titleHi: "हर यात्री की पंक्ति पढ़ें", body: "Imagine a family booking with three rows. Do not stop after reading the first passenger. Make a small private checklist for each person: current status, coach and berth. A missing field means you must verify it; do not copy a berth from another passenger's row or assume everyone has the same allocation.", bodyHi: "मान लें परिवार की बुकिंग में तीन पंक्तियाँ हैं। पहले यात्री को देखकर न रुकें। हर व्यक्ति की वर्तमान स्थिति, कोच और बर्थ निजी सूची में जाँचें। खाली जानकारी का सत्यापन करें; दूसरे यात्री की बर्थ या स्थिति सबके लिए न मानें।" },
    { title: "A practical example", titleHi: "एक व्यावहारिक उदाहरण", body: "If an example result shows booking WL/12 and current CNF, read those as an earlier waiting position and a confirmed current status. If the coach is blank, use the official enquiry to check the allocation instead of guessing a coach. This example is illustrative and is not a real ticket or a confirmation prediction.", bodyHi: "उदाहरण में बुकिंग WL/12 और वर्तमान CNF हो तो पहली जानकारी पुरानी प्रतीक्षा स्थिति और दूसरी वर्तमान कन्फर्म स्थिति है। कोच खाली हो तो अनुमान लगाने के बजाय आधिकारिक जाँच करें। यह उदाहरण है, वास्तविक टिकट या कन्फर्मेशन की भविष्यवाणी नहीं।" },
    { title: "When the two services disagree", titleHi: "दो सेवाओं के परिणाम अलग हों तो", body: "Check when each result was fetched and whether you used the same booking. Avoid repeatedly refreshing multiple tools. Open the official enquiry directly, then verify any boarding decision through railway channels. Report a display problem using the button below a RailQ result; it sends a tool identifier and problem code, not your ticket.", bodyHi: "दोनों परिणाम का समय और बुकिंग मिलाएँ। बार-बार कई टूल रिफ्रेश न करें। आधिकारिक जाँच खोलें और यात्रा का निर्णय रेलवे माध्यम से सत्यापित करें। RailQ परिणाम का समस्या बटन केवल टूल और समस्या कोड भेजता है, टिकट नहीं।" },
    { title: "Can I send my PNR to support?", titleHi: "क्या सहायता के लिए PNR भेजना चाहिए?", body: "A public screenshot is usually unnecessary. Start with the page name, what you clicked and the error message. Hide the PNR, passenger names, contact details and ticket QR code. RailQ does not need your IRCTC password, OTP or payment information to investigate a broken page.", bodyHi: "सार्वजनिक स्क्रीनशॉट सामान्यतः जरूरी नहीं है। पेज का नाम, किए गए कदम और त्रुटि बताएँ। PNR, यात्री नाम, संपर्क और टिकट QR कोड छिपाएँ। पेज की समस्या जाँचने के लिए RailQ को IRCTC पासवर्ड, OTP या भुगतान जानकारी नहीं चाहिए।" },
  ]},
  "pnr-and-waiting-lists": { checked: "16 September 2026", sources: [waitingSource, pnrSource], tools: ["pnr-status", "waitlist-guide", "trains-between-stations"], sections: [
    { title: "The final status matters", titleHi: "अंतिम स्थिति महत्वपूर्ण है", body: "For an e-ticket where every passenger remains waitlisted after charting, IRCTC says the names are removed from the chart and boarding is not permitted; cancellation and refund are processed by IRCTC. Mixed confirmed/waitlisted bookings have a different treatment. Do not apply the fully-waitlisted rule to every ticket type or a mixed family booking.", bodyHi: "ई-टिकट के सभी यात्री चार्ट के बाद भी वेटलिस्ट हों तो IRCTC के अनुसार नाम चार्ट से हटते हैं और बोर्डिंग की अनुमति नहीं होती; रद्दीकरण और रिफंड IRCTC करता है। कुछ कन्फर्म और कुछ वेटलिस्ट वाली बुकिंग अलग है। हर टिकट या मिश्रित परिवार बुकिंग पर एक नियम न लगाएँ।" },
    { title: "Plan a decision time", titleHi: "निर्णय लेने का समय तय करें", body: "Before departure day, decide when an uncertain booking becomes impractical for you. Consider travel to the station, hotel cancellation terms and the needs of children or older travellers. Keep an alternative that you can actually use, including the transfer time to a different departure station. A prediction percentage should not be the only basis for that decision.", bodyHi: "यात्रा से पहले तय करें कि कब तक अनिश्चित बुकिंग पर निर्भर रहना व्यावहारिक है। स्टेशन पहुँचने का समय, होटल रद्दीकरण और बच्चों या बुजुर्गों की जरूरतें देखें। अलग स्टेशन तक पहुँचने सहित उपयोग योग्य विकल्प रखें। केवल संभावना प्रतिशत पर निर्णय न लें।" },
    { title: "Does WL 5 guarantee confirmation?", titleHi: "क्या WL 5 कन्फर्म होने की गारंटी है?", body: "No promise should be made from that number alone. Record the quota, date, class and complete status when comparing your own checks. Different categories are not a single shared queue. RailQ's guide explains the labels; it does not sell a guaranteed upgrade or permission to travel.", bodyHi: "केवल इस संख्या से गारंटी नहीं दी जा सकती। अपनी जाँच की तुलना में कोटा, तारीख, श्रेणी और पूरा स्टेटस देखें। अलग श्रेणियाँ एक साझा कतार नहीं हैं। RailQ कोड समझाता है; गारंटीड अपग्रेड या यात्रा अनुमति नहीं बेचता।" },
    { title: "Keep money and travel decisions separate", titleHi: "रिफंड और यात्रा के निर्णय अलग रखें", body: "A refund expectation does not establish boarding permission. First establish whether you may travel using the official ticket status. Then check the applicable cancellation or claim process in your booking account. If the family has mixed statuses, ask about that exact booking situation rather than relying on an example for a single passenger.", bodyHi: "रिफंड की उम्मीद यात्रा की अनुमति नहीं है। पहले आधिकारिक टिकट स्थिति से यात्रा पात्रता जाँचें। फिर बुकिंग खाते में रद्दीकरण या दावा प्रक्रिया देखें। परिवार में मिश्रित स्थिति हो तो एक यात्री के उदाहरण पर निर्भर न रहकर उसी परिस्थिति की जानकारी लें।" },
  ]},
  "tatkal": { checked: "16 September 2026", sources: [refundSource], tools: ["tatkal-time-calculator", "booking-reminders", "seat-availability"], sections: [
    { title: "Prepare before the booking window", titleHi: "बुकिंग से पहले तैयारी करें", body: "Check the train's originating date, your boarding date and the exact station codes. They may differ on an overnight route. Choose your acceptable class and a backup option before opening the booking service. Sign in through the official IRCTC website or app and complete whatever identity or OTP checks it currently requires. RailQ never completes these checks for you.", bodyHi: "ट्रेन की शुरुआत की तारीख, अपनी बोर्डिंग तारीख और स्टेशन कोड जाँचें। रात की यात्रा में तारीखें अलग हो सकती हैं। स्वीकार्य श्रेणी और विकल्प पहले चुनें। आधिकारिक IRCTC वेबसाइट या ऐप में लॉगिन कर वहाँ माँगी गई पहचान या OTP प्रक्रिया पूरी करें। RailQ यह प्रक्रिया आपके लिए नहीं करता।" },
    { title: "Use the calculator as a reminder", titleHi: "कैलकुलेटर को रिमाइंडर मानें", body: "The calculator estimates a booking time; it neither holds inventory nor submits a booking. Confirm the opening shown by IRCTC for the selected train and class. If you download a calendar event, open it and check its date, time zone and notification setting. A downloaded file only becomes a reminder after you add it to your calendar.", bodyHi: "कैलकुलेटर समय का अनुमान देता है; सीट रोकता या टिकट बुक नहीं करता। चुनी ट्रेन और श्रेणी का समय IRCTC पर जाँचें। कैलेंडर फ़ाइल की तारीख, समय-क्षेत्र और सूचना सेटिंग देखें। फ़ाइल को कैलेंडर में जोड़ने के बाद ही रिमाइंडर बनेगा।" },
    { title: "Understand the cancellation risk", titleHi: "रद्दीकरण का जोखिम समझें", body: "IRCTC's published cancellation guidance says voluntary cancellation of a confirmed Tatkal ticket does not receive a refund. Waitlisted Tatkal and exceptional situations need their applicable rules. Choose Tatkal in the refund calculator rather than treating the ticket as a normal confirmed booking.", bodyHi: "IRCTC के प्रकाशित नियम के अनुसार कन्फर्म तत्काल टिकट स्वेच्छा से रद्द करने पर रिफंड नहीं मिलता। वेटलिस्ट तत्काल और असाधारण परिस्थितियों के अलग नियम देखें। रिफंड कैलकुलेटर में सामान्य कन्फर्म टिकट की जगह तत्काल चुनें।" },
    { title: "If payment is uncertain", titleHi: "भुगतान की स्थिति स्पष्ट न हो तो", body: "Before paying again, inspect your official booking and transaction history. Keep the transaction reference privately. A payment debit, a railway booking and a confirmed berth are different things; establish which stage completed. Do not send money to someone promising to repair a failed booking through a message or ask them to use your OTP.", bodyHi: "दोबारा भुगतान से पहले आधिकारिक बुकिंग और लेन-देन इतिहास देखें। लेन-देन संदर्भ निजी रखें। भुगतान कटना, टिकट बनना और बर्थ कन्फर्म होना अलग चरण हैं; देखें कौन-सा पूरा हुआ। संदेश पर टिकट ठीक करने का वादा करने वाले को पैसा या OTP न दें।" },
    { title: "Can RailQ guarantee a Tatkal ticket?", titleHi: "क्या RailQ तत्काल टिकट की गारंटी देता है?", body: "No. Use it to prepare dates, compare options and understand results. Complete the purchase only through your chosen authorised booking channel. The official booking confirmation is the record to keep; a RailQ calculation or calendar event is not a ticket.", bodyHi: "नहीं। RailQ तारीख की तैयारी, विकल्प और परिणाम समझने में मदद करता है। खरीद अधिकृत बुकिंग माध्यम से करें। आधिकारिक बुकिंग पुष्टि सुरक्षित रखें; RailQ की गणना या कैलेंडर इवेंट टिकट नहीं है।" },
  ]},
  "cancellation-and-refunds": { checked: "16 September 2026", sources: [refundSource], tools: ["refund-calculator", "cancellation-deadline-calculator"], sections: [
    { title: "Start with the right ticket type", titleHi: "सही टिकट प्रकार से शुरू करें", body: "Select normal or Tatkal, each passenger's status and the fare basis before calculating. For ordinary confirmed tickets the published rules use a flat charge beyond 48 hours, then 25% down to 12 hours and 50% below 12 hours down to four hours, subject to minimum charges and chart-related conditions. Do not treat the estimate as a payable promise.", bodyHi: "गणना से पहले सामान्य या तत्काल, हर यात्री की स्थिति और किराया आधार चुनें। सामान्य कन्फर्म टिकट में प्रकाशित नियम 48 घंटे से पहले तय कटौती, फिर 12 घंटे तक 25% और 12 घंटे से कम से चार घंटे तक 50% बताते हैं; न्यूनतम शुल्क और चार्ट शर्तें लागू हैं। अनुमान भुगतान की गारंटी नहीं है।" },
    { title: "Check the official action before you confirm", titleHi: "पुष्टि से पहले आधिकारिक कार्रवाई देखें", body: "Open the booking in your official account and inspect the available cancellation or claim action. Chart preparation changes the process, and the displayed options matter. Keep a private record of what you submitted and when. A calculator on another website does not cancel your ticket or file a claim.", bodyHi: "आधिकारिक खाते में बुकिंग खोलकर उपलब्ध रद्दीकरण या दावा विकल्प देखें। चार्ट के बाद प्रक्रिया बदलती है और दिख रहे विकल्प महत्वपूर्ण हैं। क्या और कब जमा किया, निजी रिकॉर्ड रखें। दूसरी वेबसाइट का कैलकुलेटर टिकट रद्द या दावा जमा नहीं करता।" },
    { title: "Compare like-for-like amounts", titleHi: "एक जैसे शुल्क आधार की तुलना करें", body: "Keep the ticket fare, service charges, taxes and any payment-provider fees separate when comparing an estimate with the final refund. Also check whether the amount shown is for one passenger or the whole booking. For a family cancelling only part of a journey, confirm which passenger rows you selected before submitting.", bodyHi: "अनुमान और वास्तविक रिफंड की तुलना में किराया, सेवा शुल्क, कर और भुगतान शुल्क अलग देखें। रकम एक यात्री की है या पूरी बुकिंग की, जाँचें। परिवार के कुछ यात्रियों का टिकट रद्द करते समय जमा करने से पहले चुनी पंक्तियाँ मिलाएँ।" },
    { title: "What if the refund has not arrived?", titleHi: "रिफंड न पहुँचे तो क्या करें?", body: "Check the cancellation confirmation and refund status in the booking account, then the original payment account. Record the reference and dates before contacting the official support channel. Keep bank account details and transaction screenshots out of public comments. RailQ cannot accelerate or approve a railway refund.", bodyHi: "बुकिंग खाते में रद्दीकरण पुष्टि और रिफंड स्थिति, फिर मूल भुगतान खाते की जाँच करें। सहायता लेने से पहले संदर्भ और तारीख नोट करें। बैंक विवरण और लेन-देन स्क्रीनशॉट सार्वजनिक न करें। RailQ रेलवे रिफंड जल्दी या स्वीकृत नहीं कर सकता।" },
  ]},
  "chart-preparation": { checked: "16 September 2026", sources: [chartSource], tools: ["chart-preparation-calculator", "pnr-status"], sections: [
    { title: "Know what the estimate represents", titleHi: "अनुमान का अर्थ समझें", body: "Central Railway's July 2025 notice describes first charting eight hours before departure, with departures from 05:00 to 14:00 charted by 21:00 the previous day. It describes final charting 30 minutes before departure. Use this as published guidance, not a guarantee for every train or intermediate boarding point; check the actual chart status.", bodyHi: "मध्य रेलवे की जुलाई 2025 सूचना पहला चार्ट आठ घंटे पहले और 05:00 से 14:00 के प्रस्थान के लिए पिछले दिन 21:00 तक बताती है। अंतिम चार्ट प्रस्थान से 30 मिनट पहले बताया गया है। इसे प्रकाशित मार्गदर्शन मानें, हर ट्रेन या बीच के बोर्डिंग स्टेशन की गारंटी नहीं; वास्तविक चार्ट स्थिति जाँचें।" },
    { title: "Origin and boarding point are different", titleHi: "शुरुआती और बोर्डिंग स्टेशन अलग हैं", body: "Suppose a train begins its route the previous evening and reaches your boarding station the next morning. Entering your local departure time without checking the applicable charting location can produce a misleading estimate. Keep the train's origin, your boarding station and travel date together when verifying the result through railway channels.", bodyHi: "मान लें ट्रेन पिछले दिन शाम को शुरू होकर अगली सुबह आपके स्टेशन पहुँचती है। लागू चार्टिंग स्थान जाँचे बिना स्थानीय समय डालने से अनुमान गलत हो सकता है। रेलवे माध्यम से सत्यापन में ट्रेन की शुरुआत, बोर्डिंग स्टेशन और तारीख साथ रखें।" },
    { title: "Set two separate checks", titleHi: "दो अलग जाँच रखें", body: "First, plan when to review the booking before leaving home. Second, verify the current PNR and station information before boarding. A chart-time estimate does not establish a platform or coach position. Keep enough travel buffer for the station and do not leave cancellation decisions to an unverified countdown.", bodyHi: "पहले घर से निकलने से पहले बुकिंग जाँचने का समय तय करें। फिर बोर्डिंग से पहले वर्तमान PNR और स्टेशन जानकारी जाँचें। चार्ट का अनुमान प्लेटफॉर्म या कोच स्थिति तय नहीं करता। स्टेशन पहुँचने का समय रखें और रद्दीकरण का निर्णय अपुष्ट काउंटडाउन पर न छोड़ें।" },
    { title: "Why has my expected chart time passed?", titleHi: "अनुमानित समय बीत गया तो?", body: "Check the official chart status instead of assuming preparation has finished. A third-party result may be old, unavailable or based on the wrong date. Compare the fetched time and correct the input where necessary. If you report the issue, describe the tool and error without posting your ticket details.", bodyHi: "चार्ट तैयार मानने के बजाय आधिकारिक स्थिति देखें। तीसरे पक्ष का परिणाम पुराना, अनुपलब्ध या गलत तारीख पर आधारित हो सकता है। परिणाम का समय मिलाएँ और जरूरत पर इनपुट ठीक करें। समस्या बताते समय टूल और त्रुटि बताएँ, टिकट विवरण नहीं।" },
  ]},
};
